import "./globals.css";

import type { Metadata } from "next";
import { Numans } from "next/font/google";

import { ThemeTogglerProvider } from "@/contexts/theme-toggler-context";

const numans = Numans({
  variable: "--font-numans-sans",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${numans.className} antialiased`}>
        <ThemeTogglerProvider>{children}</ThemeTogglerProvider>
      </body>
    </html>
  );
}
